name: paperwise
description: AI-powered paper reading assistant powered by MinerU and DeepSeek.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter

  dio: any
  dio_smart_retry: any
  file_picker: any
  path_provider: any
  shared_preferences: any
  archive: any
  flutter_markdown: any
  flutter_math_fork: any
  window_manager: any
  tray_manager: any
  url_launcher: any
  connectivity_plus: any
  flutter_riverpod: any
  logging: any
  uuid: any
  intl: any
  share_plus: any
  synchronized: any
  path: any
  syncfusion_flutter_pdf: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  mocktail: any

flutter:
  uses-material-design: true
  assets:
    - resources/
